### ISSUE TITLE
FileNotFound when attempting to build

### ISSUE THREAD

**Issue by mskyttner** [kimmolinna/duckdb-zig-build#1]
After cloning this repo, I tried checking out the files for duckdb master branch at the time for the last update of this repo and build with those file in a subdir, using:

```bash
if [ ! -d "duckdb" ]; then git clone https://github.com/duckdb/duckdb.git; fi
cp build.zig duck_files.zig duckdb
cd duckdb && git checkout 'master@{2021-01-07 00:00:00}' && zig build
```
But there were some complaints about missing files, for example `duckdb/src/execution/merge_join/merge_join_complex.cpp` etc.

I tried also using `git clone https://github.com/kimmolinna/duckdb.git` in case those files were more in sync.

It would be nice with for example this [gha](https://github.com/marketplace/actions/setup-zig) for building, but I couldn't try that out since it looked like the duck_files.zig referred to files not present in the duckdb repo?

Any hints?

**Comment by kimmolinna** [comment]
I updated the version for a while ago but I forget to update it thus files weren't in sync with DuckDB. Now it should work.
